export const santaFeCourts = [
  // --- CÁMARAS DE APELACIÓN ---
  "Cámara Apelaciones Civil y Comercial (Sala I)",
  "Cámara Apelaciones Civil y Comercial (Sala II)",
  "Cámara Apelaciones Civil y Comercial (Sala III)",
  "Cámara Apelaciones Civil y Comercial (Sala IV)",
  "Cámara Apelaciones Civil y Comercial (Sala V)",
  "Cámara de Apelación de Circuito de Rosario",
  "Cámara de Apelación Laboral (Sala I)",
  "Cámara de Apelación Laboral (Sala II)",
  "Cámara de Apelación Laboral (Sala III)",
  "Cámara de lo Contencioso Administrativo de Rosario",

  // --- JUZGADOS CIVIL Y COMERCIAL ---
  "Juzg. 1ra. Inst. Civil y Comercial 1ra. Nom.",
  "Juzg. 1ra. Inst. Civil y Comercial 2da. Nom.",
  "Juzg. 1ra. Inst. Civil y Comercial 3ra. Nom.",
  "Juzg. 1ra. Inst. Civil y Comercial 4ta. Nom.",
  "Juzg. 1ra. Inst. Civil y Comercial 5ta. Nom.",
  "Juzg. 1ra. Inst. Civil y Comercial 6ta. Nom.",
  "Juzg. 1ra. Inst. Civil y Comercial 7ma. Nom.",
  "Juzg. 1ra. Inst. Civil y Comercial 8va. Nom.",
  "Juzg. 1ra. Inst. Civil y Comercial 9na. Nom.",
  "Juzg. 1ra. Inst. Civil y Comercial 10ma. Nom.",
  "Juzg. 1ra. Inst. Civil y Comercial 11ra. Nom.",
  "Juzg. 1ra. Inst. Civil y Comercial 12da. Nom.",
  "Juzg. 1ra. Inst. Civil y Comercial 13ra. Nom.",
  "Juzg. 1ra. Inst. Civil y Comercial 14ta. Nom.",
  "Juzg. 1ra. Inst. Civil y Comercial 15ta. Nom.",
  "Juzg. 1ra. Inst. Civil y Comercial 16ta. Nom.",
  "Juzg. 1ra. Inst. Civil y Comercial 17ta. Nom.",
  "Juzg. 1ra. Inst. Civil y Comercial 18va. Nom.",
  "Juzg. 1ra. Inst. Civil y Comercial 19na. Nom.",
  "Juzg. 1ra. Inst. Civil y Comercial 20ma. Nom.",
  "Juzg. 1ra. Inst. Civil y Comercial 21ra. Nom.",
  "Juzg. 1ra. Inst. Civil y Comercial 22da. Nom.",

  // --- FAMILIA ---
  "Tribunal Colegiado Familia Nro. 3",
  "Tribunal Colegiado Familia Nro. 4",
  "Tribunal Colegiado Familia Nro. 5",
  "Tribunal Colegiado Familia Nro. 7",
  "Juzg. Unipersonal de Familia N° 1",
  "Juzg. Unipersonal de Familia N° 2",
  "Juzg. Unipersonal de Familia N° 3",
  "Juzg. Unipersonal de Familia N° 4",
  "Juzg. Unipersonal de Familia N° 5",
  "Juzg. Unipersonal de Familia N° 6",
  "Juzg. Unipersonal de Familia N° 7",
  "Juzg. Unipersonal de Familia N° 8",
  "Juzg. Unipersonal de Familia N° 9",
  "Juzg. Unipersonal de Familia N° 10",
  "Juzg. Unipersonal de Familia N° 11",
  "Juzg. Unipersonal de Familia N° 12",
  
  // --- LABORAL ---
  "Juzg. 1ra. Inst. Laboral 1ra. Nom.",
  "Juzg. 1ra. Inst. Laboral 2da. Nom.",
  "Juzg. 1ra. Inst. Laboral 3ra. Nom.",
  "Juzg. 1ra. Inst. Laboral 4ta. Nom.",
  "Juzg. 1ra. Inst. Laboral 5ta. Nom.",
  "Juzg. 1ra. Inst. Laboral 6ta. Nom.",
  "Juzg. 1ra. Inst. Laboral 7ma. Nom.",
  "Juzg. 1ra. Inst. Laboral 8va. Nom.",
  "Juzg. 1ra. Inst. Laboral 9na. Nom.",
  "Juzg. 1ra. Inst. Laboral 10ma. Nom.",

  // --- CIRCUITO Y RESPONSABILIDAD EXTRACONTRACTUAL ---
  "Juzg. de 1ra. Instancia de Circuito N°1",
  "Juzg. de 1ra. Instancia de Circuito N°2",
  "Juzg. de 1ra. Instancia de Circuito N°3",
  "Juzg. de 1ra. Instancia de Circuito N°4",
  "Juzg. de 1ra. Instancia de Circuito N°5",
  "Trib. Coleg. Resp. Extracontractual - 1ra. Nom.",
  "Trib. Coleg. Resp. Extracontractual - 2da. Nom.",
  "Trib. Coleg. Resp. Extracontractual - 6ta. Nom.",
  "Juzg. Unipersonal de Respons. Extrac. N° 1",
  "Juzg. Unipersonal de Respons. Extrac. N° 2",
  "Juzg. Unipersonal de Respons. Extrac. N° 3",
  "Juzg. Unipersonal de Respons. Extrac. N° 4",
  "Juzg. Unipersonal de Respons. Extrac. N° 5",
  "Juzg. Unipersonal de Respons. Extrac. N° 6",
  "Juzg. Unipersonal de Respons. Extrac. N° 7",
  "Juzg. Unipersonal de Respons. Extrac. N° 8",
  "Juzg. Unipersonal de Respons. Extrac. N° 9",
  "Juzg. Unipersonal de Respons. Extrac. N° 10",

  // --- OTROS ---
  "Registro Público",
  "Oficina de Procesos Sucesorios",
  "Juzgado de 1ra. Inst. de Ejecución de Distrito - 1era. Nom.",
  "Juzgado de 1ra. Inst. de Ejecución de Distrito - 2da. Nom.",
  "Juzgado de Feria (Civil/Comercial/Circuito)",
  "Juzgado de Feria (Laboral)",
  "Juzgado de Feria (Familia)"
].sort();